#!/usr/bin/dumb-init ash

set -e

if [[ -z "$CRON" ]]; then
    echo "error: 'CRON' variable is required"
    exit 1
fi
if [[ -z "$COMMAND" ]]; then
    echo "error: 'COMMAND' variable is required"
    exit 1
fi

cron_path="/cron"

echo "# generated by /init.sh
$CRON   $COMMAND" > "$cron_path/$(whoami)"

exec crond -f -d 0 -c /cron